/* 
    Edit table.
    1. Add new column -> ALTER TABLE ADD ...
    2. Delete column -> ALTER TABLE DROP COLUMN ...
    3. Edit column -> ALTER TABLE ALTER COLUMN ...
    4. Add constraint -> ALTER TABLE ADD CONSTRAINT ...
    5. Delete constraint -> ALTER TABLE DROP CONSTRAINT ...
    6. Edit constraint -> first delete, then add new constraint
    ALTER TABLE 

*/ 
USE JobsDB

-- 1. Add new column -> ALTER TABLE ADD ...
ALTER TABLE Employees ADD Address NVARCHAR(350) NULL

-- 2. Delete column -> ALTER TABLE DROP COLUMN ...
ALTER TABLE Employees DROP COLUMN Address

-- 3. Edit column -> ALTER TABLE ALTER COLUMN ...
ALTER TABLE Employees ALTER COLUMN Address NVARCHAR(250) NOT NULL

-- 4. Add constraint -> ALTER TABLE ADD CONSTRAINT ...
ALTER TABLE Employees ADD CONSTRAINT UQ_Address UNIQUE(Address)

-- 5. Delete constraint -> ALTER TABLE DROP CONSTRAINT ...
ALTER TABLE Employees DROP CONSTRAINT UQ_Address

-- 6. Edit constraint -> first delete, then add new constraint
ALTER TABLE Employees DROP CONSTRAINT UQ_Address
ALTER TABLE Employees ADD CONSTRAINT UQ_Address UNIQUE(Address)
